### ISSUE TITLE
SML writer problems

### ISSUE THREAD

**Issue by hk-moon** [arrogant1998/SECS#1]
Thank you for good release.

I tested, but some problems in PrintMessage.cs [<TF [2] "System.Boolean[]">].
What is meaning of "System.Boolean[]" ?
Please check below log and advice of return.

[20:37:31.108] Receive 'S16F15' W id:(2034627)
'S16F15' W
<L [2]
    <U4 [1] 0 >
    <L [1]
        <L [6]
            <A [1] "P">
            <B [1] 0x0d >
            <L [1]
                <L [2]
                    <A [1] "A">
                    <L [2]
                        <U1 [1] 3 >
                        <U1 [1] 5 >
                    >
                >
            >
            <L [3]
                <U1 [1] 1 >
                <A [1] "9">
                <L [0]
                >
            >
ThirdList : 2th Line = TF
            <TF [2] "System.Boolean[]">
            <L [0]
            >
        >
    >
>
.
[20:38:15.810] Receive Cotrol Message: Linktest_req
[20:38:15.811] Sent Control message: Linktest_rsp

**Comment by arrogant1998** [comment]
Hi hk-moon:

This is a bug that occurs when printing TF. 
It has already been modified in PrintMessage.cs.
You can test it again. 

Thank you for your usage and response.

**Comment by hk-moon** [comment]
I checked PrintMessage.cd and Boolean issue cleared.
thank you for your kinds.
